#!/usr/bin/env bash
# A script that transfers a file from our client to a server
# takes 4 parameters

if [ $# -lt 4 ]; then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
	exit 1

fi
scp -i $4 -o StrictHostKeyChecking=n0 $1 $3@$2:~/$1
