#!/usr/bin/env bash
# A script that Install nginx on my web-01

apt update
apt install nginx -y

sed -1 's/listen [::]:80 default_server;/listen 80;/g' /etc/nginx/sites-availables/default

cat <<EOF > /var/www/html/index..html
Hello Wold!
EOF

service nginx restart
