#!/usr/bin/env bash
# installs nginx and configure to listen on port 80

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudon chown -R ubuntu:ubuntu /var/www
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
