#!/usr/bin/env bash
# automates nginx setup

sudo apt update
sudo apt install nginx -y 
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx
echo 'Hello World!' | sudo tee /var/www/html/index/.html > /dev/null
sudo service nginx restart

