#!/usr/bin/env bash
# script that installs Nginx server and redirects /redirect_me to
# another page
# The redirection must be a “301 Moved Permanently”
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP" # allow incoming connections from nginx
# sudo ufw status verbose: should return inactive
cd /var/www/ || exit
sudo chmod 777 html
echo "Hello World!" > html/index.html
sudo chmod 755 html
# Configure your Nginx server to redirect to another page
NGINX_CONFIG_PATH="/etc/nginx/sites-enabled/default"
REDIRECT_CONFIG="\tlocation /redirect_me {\n\t\treturn 301 https://www.alxafrica.com;\n\t}"
sudo sed -i "/server {/a $REDIRECT_CONFIG" "$NGINX_CONFIG_PATH"
sudo service nginx restart
