#!/usr/bin/env bash
# script that doubles the number of webservers and adds new configs

# install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set custom HTTP header in Nginx
echo "add_header X-Served-By \$hostname;" | sudo tee -a /etc/nginx/nginx.conf

# restart Nginx
sudo systemctl restart nginx
