#!/usr/bin/env bash
#displays "Best School" 10 times, with "Hi" on a new line.

count=0

while [ $count -lt 10 ]; do
	if [ $count -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
