#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install ufw
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

sudo ufw default deny incoming  # Deny all incoming traffic by default
sudo ufw default allow outgoing # Allow all outgoing traffic by default

# Allow SSH (port 22), HTTP (port 80), and HTTPS (port 443) incoming traffic
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable UFW
sudo ufw enable
